### ISSUE TITLE
Wagtail API Breaks on Page Detail With Choosers

### ISSUE THREAD

**Issue by ephes** [ephes/django-cast#157]
Saw this traceback for pages with image and video choosers:
```python
Traceback (most recent call last):
  File "/Users/jochen/.virtualenvs/homepage/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jochen/.virtualenvs/homepage/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jochen/.pyenv/versions/3.12.4/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/jochen/.virtualenvs/homepage/lib/python3.12/site-packages/wagtail/api/v2/router.py", line 68, in wrapped
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jochen/.virtualenvs/homepage/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jochen/.virtualenvs/homepage/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jochen/.virtualenvs/homepage/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jochen/.virtualenvs/homepage/lib/python3.12/site-packages/wagtail/api/v2/views.py", line 132, in handle_exception
    return super().handle_exception(exc)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jochen/.virtualenvs/homepage/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jochen/.virtualenvs/homepage/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
    ^^^^^^^^^
  File "/Users/jochen/.virtualenvs/homepage/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jochen/.virtualenvs/homepage/lib/python3.12/site-packages/wagtail/api/v2/views.py", line 89, in detail_view
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/Users/jochen/.virtualenvs/homepage/lib/python3.12/site-packages/rest_framework/serializers.py", line 571, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/jochen/.virtualenvs/homepage/lib/python3.12/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jochen/.virtualenvs/homepage/lib/python3.12/site-packages/wagtail/api/v2/serializers.py", line 348, in to_representation
    data[field.field_name] = field.to_representation(attribute)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jochen/.virtualenvs/homepage/lib/python3.12/site-packages/wagtail/api/v2/serializers.py", line 265, in to_representation
    return value.stream_block.get_api_representation(value, self.context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jochen/.virtualenvs/homepage/lib/python3.12/site-packages/wagtail/blocks/stream_block.py", line 363, in get_api_representation
    "value": child.block.get_api_representation(
             
  File "/Users/jochen/.virtualenvs/homepage/lib/python3.12/site-packages/wagtail/blocks/stream_block.py", line 363, in get_api_representation
    "value": child.block.get_api_representation(
             
  File "/Users/jochen/.virtualenvs/homepage/lib/python3.12/site-packages/wagtail/blocks/base.py", line 265, in get_api_representation
    return self.get_prep_value(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jochen/.virtualenvs/homepage/lib/python3.12/site-packages/wagtail/blocks/field_block.py", line 831, in get_prep_value
    return value.pk
           ^^^^^^^^

Exception Type: AttributeError at /blogs/api/wagtail/pages/14/
Exception Value: 'int' object has no attribute 'pk'
```

**Comment by ephes** [comment]
It's still broken:
```python
'dict' object has no attribute 'pk'
    def get_prep_value(self, value):
        # the native value (a model instance or None) should serialise to a PK or None
        if value is None:
            return None
        else:
            return value.pk  # <-- here
```
